language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # TODO 3.7 when travis supports it
install:
  - pip install -e .
script:
  - python -m unittest -v pandas_profiling.tests
